[package]
name = "mira-moba"
version = "0.1.0"
edition = "2024"
authors = ["Daniel Ramke <genshin.exepta@outlook.com>"]
exclude = ["dist", "build", "assets", "credits", "conf"]

[[bin]]
name = "mira-moba"
path = "src/main.rs"

[profile.release]
panic = "unwind"
opt-level = "s"
lto = true
codegen-units = 1
strip = true

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
debug = true

[package.metadata.llvm-cov]
# Ignore files for code cov

# Release & Dev
[dependencies.bevy]
version = "0.16.1"
default-features = false
features = [
    "bevy_asset",
    "bevy_core_pipeline",
    "bevy_log",
    "bevy_render",
    "bevy_window",
    "bevy_winit",
    "default_font",
    "multi_threaded",
    "x11"
]

[dependencies.bevy-inspector-egui]
version = "0.31.0"

[dependencies.tracing-subscriber]
version = "0.3.19"

[dependencies.chrono]
version = "0.4.41"