[package]
name = "mira-echoes-of-ash"
version = "0.1.0"
edition = "2024"
authors = ["Daniel Ramke <genshin.exepta@outlook.com>", "Felix Werner <flexwurm@gmail.com>"]
exclude = ["dist", "build", "assets", "credits", "conf"]

[[bin]]
name = "mira-echoes-of-ash"
path = "src/main.rs"

[workspace]
members = [
    "crates/game_ui",
    "crates/game_load",
    "crates/game_system",
    "crates/game_logic",
    "crates/game_environment",
    "crates/game_audio",
    "crates/game_network"
]

[profile.release]
panic = "unwind"
opt-level = "s"
lto = true
codegen-units = 1
strip = true

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
debug = true

# Innternal crates
[dependencies]
game_system = { path = "crates/game_system" }
game_ui = { path = "crates/game_ui" }
game_load = { path = "crates/game_load" }
game_logic = { path = "crates/game_logic" }
game_environment = { path = "crates/game_environment" }
game_audio = { path = "crates/game_audio" }
game_network = { path = "crates/game_network" }

# Release & Dev
[dependencies.bevy]
version = "0.16.1"
default-features = true
features = [
    "bevy_asset",
    "bevy_core_pipeline",
    "bevy_gltf",
    "bevy_log",
    "bevy_render",
    "bevy_window",
    "bevy_winit",
    "default_font",
    "multi_threaded",
    "x11"
]

# Rapier3D supported
[dependencies.bevy_rapier3d]
version = "0.30.0"
features = ["simd-nightly", "debug-render-3d", "default"]

[dependencies.bevy-inspector-egui]
version = "0.31.0"

[dependencies.tracing-subscriber]
version = "0.3.19"

[dependencies.chrono]
version = "0.4.41"
features = ["clock"]

# Only dev
[dev-dependencies.tempfile]
version = "3.20.0"