[package]
name = "game_load"
version = "0.0.1"
edition = "2024"
authors = ["Daniel Ramke <genshin.exepta@outlook.com>"]

[lib]
name = "game_load"
path = "src/lib.rs"

[dependencies.game_system]
path = "../game_system"

[dependencies.bevy]
version = "0.16.1"
default-features = true
features = ["bevy_log"]

[dependencies.serde]
version = "1.0.219"
features = ["derive"]

[dependencies.serde_json]
version = "1.0.142"