[package]
name = "game_load"
version = "0.0.1"
edition = "2024"
authors = ["Daniel Ramke <genshin.exepta@outlook.com>"]

[lib]
name = "game_load"
path = "src/lib.rs"

[dependencies.bevy]
version = "0.16.1"
default-features = false
features = [
    "bevy_asset",
    "bevy_core_pipeline",
    "bevy_render",
    "bevy_log",
    "bevy_text",
    "default_font",
    "multi_threaded",
    "png",
    "jpeg"
]