player_up = "W"
player_down = "S"
player_left = "A"
player_right = "D"
player_sprint = "ShiftLeft"
player_interact = "F"
open_inventory = "B"
menu_key = "Escape"
battle_attack_0 = "Q"
battle_spell_0 = "E"
battle_ultimate = "Space"
character_01 = "1"
character_02 = "2"
character_03 = "3"
character_04 = "4"
debug_change = "F3"
world_inspector_ui = "F1"
show_cursor = "AltLeft"
camera_vertical_sensitivity = 2.0
camera_horizontal_sensitivity = 2.0
camera_zoom_in = 1.5
camera_zoom_out = 10.0
