[package]
name = "game_audio"
version = "0.0.1"
edition = "2024"
authors = ["Daniel Ramke <genshin.exepta@outlook.com>"]

[lib]
name = "game_audio"
path = "src/lib.rs"

[dependencies.game_system]
path = "../game_system"

[dependencies.bevy]
version = "0.16.1"
default-features = false
features = [
    "bevy_log",
    "bevy_asset",
    "bevy_core_pipeline",
    "multi_threaded",
]

[dependencies.bevy_kira_audio]
version = "0.23.0"
features = ["ogg", "flac", "wav"]