[package]
name = "game_network"
version = "0.1.0"
edition = "2024"

[lib]
name = "game_network"
path = "src/lib.rs"

[dependencies.bevy]
version = "0.16.1"
default-features = false
features = [
    "bevy_log",
]

[dependencies.game_core]
path = "../game_core"

[dependencies.bevy_http_client]
version = "0.8.3"